# This workflow uses actions 
# https://www.youtube.com/watch?v=kh7piyS2XeE
# https://crontab.guru - The quick and simple editor for cron schedule expressions by Cronitor



name: Trigger Action on a CRON Schedule

on:
  schedule:
    # At 11:00 on every day-of-week from Monday through Friday
    - cron: '0 11 * * 1-5'

jobs:
  build:
    name: Trigger Code Checkout
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
        - uses: actions/checkout@v3

     
