# This workflow uses actions 
# https://www.youtube.com/watch?v=u-TcADhWosA


name: import-data

on:
  push:
    branches: main

jobs:
  import-data:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Sets up the js to run
        - name: Set up R
          uses: r-lib/actions/setup-r@v2

   # Install any packages that are needed for the js to run
        - name: Install packages
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            packages: |
              any::tidyverse
              any::googlesheets4
              
 # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
        - name: Import data
          run: Rscript -e 'source("import-data.R")'

        - name: Commit results
          run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git add survey_data.rds
            git commit -m 'Data updated' || echo "No changes to commit"
            git push origin || echo "No changes to commit"
          
              

          

     
